### ISSUE TITLE
Remove Bitcoin Lib dependency

### ISSUE THREAD

**Issue by owenvoke** [arionum/json-rpc#5]
I propose that we remove the [bitcoin-lib] package from Composer. The only place the bitcoin library seems to be used is on [line 430][rawtransaction-usage] of `index.php`.

```php
RawTransaction::encode($t)
```

This package has been deprecated for 3 years (Bit-Wasp/bitcoin-lib-php#104), and shouldn't be used. It's also incompatible with PHP 7.2 due to its explicit requirement of the `php-mcrypt` extension which is no longer available in PHP.

They recommend moving to the [bitcoin-php] package, but as the only feature used from it was the RawTransaction which no longer seems to be a feature in the new package, we could probably quite easily remove the use of this method and custom-write a new implementation to replace it.

[bitcoin-lib]: https://github.com/Bit-Wasp/bitcoin-lib-php
[bitcoin-php]: https://github.com/Bit-Wasp/bitcoin-php
[rawtransaction-usage]: https://github.com/arionum/json-rpc/blob/master/index.php#L430

**Comment by arionum** [comment]
I agree with this. We will remove it.

**Comment by arionum** [comment]
Implemented
